### ISSUE TITLE
Create User shows up twice

### ISSUE THREAD

**Issue by orschiro** [clarkwinkelmann/flarum-ext-create-user-modal#11]
Hi all,

Anyone else able to reproduce this visual glitch?

![image](https://user-images.githubusercontent.com/170947/175044500-65574964-2631-4a90-a9f9-8aadfc9cb465.png)

**Comment by clarkwinkelmann** [comment]
Can you check the javascript console under your browser development tools for any javascript error message?

Alternatively, can you share your website URL so I can take a look? (I should be able to check what is wrong without any need to login)

This kind of glitch happens if a javascript error is thrown from inside a Mithril component template, and this causes Mithril to start redrawing the component again thinking the previous attempt failed, while in fact leaving an incomplete ghost element behind.

**Comment by orschiro** [comment]
@clarkwinkelmann thanks!

The URL is community.sheetgo.com.

This is the error.

```
mount-redraw.js:15 TypeError: Cannot read properties of undefined (reading 'filter')
    at e.<anonymous> (DiscussionControls']":14:41)
    at Wr.forEach.t.<computed> [as items] (extend.ts:39:16)
    at n.view (LogInButtons.js:9:48)
    at Function.a (render.js:30:16)
    at render.js:155:45
    at render.js:160:3
    at c (render.js:66:8)
    at l (render.js:50:5)
    at render.js:134:5
    at c (render.js:63:14)
```

**Comment by clarkwinkelmann** [comment]
I have pushed version 1.3.1 which should fix the issue.

Let me know if the problem persists and I'll re-open!

**Comment by orschiro** [comment]
Thank you!
